// products.js
const products = [
  [
    {
      id: 1,
      name: "Classic Gold Leather",
      price: 695,
      category: "Luxury",
      img: "/Classic_Gold1.png",
      brand: "Caveman Watches",
      desc: "Stainless steel case with leather strap",
    },
    {
      id: 2,
      name: "Classic Rose Gold",
      price: 299,
      category: "Luxury",
      img: "/Classic_Rose-Gold.png",
      brand: "Caveman Watches",
      desc: "Stainless steel case with leather strap",
    },
  ],
  [
    {
      id: 3,
      name: "Retro Idol Black",
      price: 695,
      category: "Casual",
      img: "/RetroIdol_black1.png",
      brand: "Caveman Watches",
      desc: "Sleek rectangular stainless steel case",
    },
    {
      id: 4,
      name: "Retro Idol Gold",
      price: 299,
      category: "Casual",
      img: "/RetroIdol_gold1.png",
      brand: "Caveman Watches",
      desc: "Sleek rectangular stainless steel case",
    },
  ],
  [
    {
      id: 5,
      name: "Classic Gold Leather",
      price: 695,
      category: "Luxury",
      img: "/Classic_Gold1.png",
      brand: "Caveman Watches",
      desc: "Stainless steel case with leather strap",
    },
    {
      id: 6,
      name: "Classic Rose Gold",
      price: 299,
      category: "Luxury",
      img: "/Classic_Rose-Gold.png",
      brand: "Caveman Watches",
      desc: "Stainless steel case with leather strap",
    },
  ],
  [
    {
      id: 7,
      name: "Essentials SWR054",
      price: 215,
      category: "Quartz",
      img: "/SWR054.png",
      brand: "Seiko Group",
      desc: "Stainless steel case with gold finish",
    },
    {
      id: 8,
      name: "Essentials SWR066",
      price: 215,
      category: "Quartz",
      img: "/SWR066.png",
      brand: "Seiko Group",
      desc: "Stainless steel case with gold finish",
    },
  ],
  [
    {
      id: 9,
      name: "Prospex SSC817",
      price: 695,
      category: "Sport",
      img: "/SSC817.png",
      brand: "Seiko Group",
      desc: "Seiko Speedtimer Solar Chronograph",
    },
    {
      id: 10,
      name: "Prospex SSC819",
      price: 299,
      category: "Sport",
      img: "/SSC819.png",
      brand: "Seiko Group",
      desc: "Seiko Speedtimer Solar Chronograph",
    },
  ],
];

export default products;
