import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import Footer from "./components/Footer";
import Marquee from "./components/Marquee";

const redHat = Red_Hat_Display({
  variable: "--font-red-hat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={redHat.variable}>
      <body className="antialiased font-sans">
        <Marquee />
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
